### ISSUE TITLE
Missing textAppearance()

### ISSUE THREAD

**Issue by marcin-kozinski** [anvil-ui/anvil#62]
A method to set text appearance is missing from the set of generated attr methods.

I would expect to be able to do something like that (in Kotlin):

``` kotlin
textView {
    textAppearance(android.R.style.TextAppearance_Material_Display1)
}
```

but currently there is no existing method for that.

I've seen you explain in one of the closed issues that methods for setters with multiple arguments are not generated and you have to add them by hand. This however takes just one argument, so it seems weird it's been omitted.

I can write the method myself, but I think it would be nice to be able to import from the `DSL` class like all the other methods. My implementation looks like that:

``` kotlin
private fun textAppearance(textAppearance: Int) =
        attr(Anvil.AttrFunc { textView, new: Int, old ->
            (textView as TextView).setTextAppearance(new)
        }, textAppearance)
```

**Comment by zserge** [comment]
It takes one argument for API level 23. On ealier API levels it takes 2 arguments, so it's correct that DSL bindings are not generated.

http://developer.android.com/reference/android/widget/TextView.html#setTextAppearance(int)

Here we can make a wrapper for the single argument function (like in API level 23) and pass the current view context instead.

**Comment by marcin-kozinski** [comment]
Aaah, cool, that explains it, I didn't notice that 👍 

So it would be nice to have a manually written method for that. I'll try to submit a PR if I have the time, but no promises as to when that could be.
