### ISSUE TITLE
Quirk with xml views and IDs

### ISSUE THREAD

**Issue by danhawkes** [anvil-ui/anvil#65]
Not sure if much can be done about this, but perhaps it should be documented somewhere.

If I inflate a view tree where view IDs arent't globally unique, e.g.

```
linearlayout id=1
   edittext id=2, text=a
   edittext id=2, text=b
   edittext id=2, text=c
```

When the edittexts' state is saved and restored, the wrong value is set on 2/3 of them because [view state is keyed by the view's ID](http://stackoverflow.com/questions/20405526/why-does-android-change-the-value-of-edittexts-with-same-id).

```
linearlayout id=1
   edittext id=2, text=a
   edittext id=2, text=a
   edittext id=2, text=a
```

This creates a problem when setting the text with Anvil, as for example `text("b")` is a no-op because as far as Anvil's concerned the view's value is already "b".

**Comment by zserge** [comment]
@danhawkes Ok, it's strange. Why do the views have the same IDs? Is it an adapter you're using or a for-loop? And why the views can't have incremented IDs?
You may override IDs with Anvil I think if that helps.

Still, sorry, the whole situation and the constraints are not really clear to me, so I'd be glad to help if you tell me more.

**Comment by danhawkes** [comment]
> Why do the views have the same IDs? 

Think there's a couple of common patterns:

- `some_layout` has an ID set somewhere in it:

        <LinearLayout>
          <include layout="@layout/some_layout"/>
          <include layout="@layout/some_layout"/>
          <include layout="@layout/some_layout"/>
        </LinearLayout>

- or, a custom view inflates a layout with constant IDs so it can configure its subviews programmatically:

        <LinearLayout>
          <CustomView app:someAttr="lalala"/>
          <CustomView app:someAttr="lololo"/>
        </LinearLayout>
        
        class CustomView {

            CustomView(Context context) {
               View view = layoutInflater.inflate(R.layout.some_layout, …);
               TextView t = view.findViewById(…);
               t.setText("a custom view");
            }
        }

Am not sure about overriding IDs to make them unique - I think that risks breaking the implementation of CustomView if it calls findViewById after construction expecting to find something declared in the inflated layout. Guess this is just a limitation of mixing code/XML (which has always been painful). Foir what it's worth I've just started rewriting affected views in the DSL.

**Comment by zserge** [comment]
Thanks for the clarification.

Since Anvil has nothing to do with onSaveInstanceState I wonder how it is supposed to work with just XMLs? Will the contents be still overridden if the parent views have different IDs? I mean when saving view state - is it only view ID that is the key, or some combination of all parent IDs in the hierarchy as well?

If there is a way to resolve it with just XMLs - I'm happy to consider a similar fix for Anvil, but if the XMLs themselves are broken - I don't think Anvil could gracefully work with it.

**Comment by danhawkes** [comment]
As far as I can tell, state saving doesn't work with non-globally unique view IDs, regardless of whether they're from XML or not. Here's the [relevant bit in the source][1], showing view state being keyed with just the view's ID. Can't find where the SparseArray is coming from, but the fact it's passed as an argument makes it seem likely it's global state.

The problem is more easily fixable in 'regular' view code because the native setX() APIs don't typically check whether a change is required before making it, whereas Anvil makes the call a no-op.

Potentially this could be worked around by:
- providing support for something like `Anvil.invalidateCache()` that would discard the `Attr` state in each view node, and ideally…
- detecting view state restoration and doing the above automatically when there are duplicate IDs in the view tree

[1]: http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/view/View.java#14672
